version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper2
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    image: captainji/jupyterlab:3.0.5
    container_name: jupyterlab3
    ports:
      - "8888:8888"
    volumes:
      - /opt/notebooks
    